server:
  port: 9000
dubbo:
  application:
    name: dubbo-root-service
  registry:
    address: zookeeper://${REGISTRY_HOST:127.0.0.1}:2181
  protocol:
    name: dubbo
    port: ${PROTOCOL_PORT:20880}