server:
  port: 9001
dubbo:
  application:
    name: dubbo-middle-service
  registry:
    address: zookeeper://${REGISTRY_HOST:127.0.0.1}:2181
  protocol:
    port: ${PROTOCOL_PORT:20881}
    name: ${PROTOCOL_NAME:dubbo}